step_class:
  create: 10
  approve: 20
  confirm: 30
  archive: 90
step_order:
  create: 0
  archive: 100
step_operator:
  and: 10
  or: 20
step_event_class:
  create: 100
  update: 200
  delete: -1

person_event_class:
  create: 100
  application: 110
  rejected: 120
  approve_request: 200
  approve: 210
  reject: 220
  rejected: 230
  skip: 240
  confirm_request: 300
  confirm: 310
  skip_backward: 800
  archive: 900
